### ISSUE TITLE
[Bug]: Various problems with PlayReady

### ISSUE THREAD

**Issue by SoNothingMC** [ciderapp/Sabiiro-BugTracker#101]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

https://discord.com/channels/843954443845238864/905459703092490340/1087210306331222097  
Installer SHA256: `1DD588DD876B2260E1649594B18C0EFFEC829A9DA1EF5F01A6AB5E606F8C4E51`

### Operating System Version

Windows 10 22H2 (19045.2604)

### Describe the Bug

I have been talking about getting random "Playback Error" messages in public and in private* for the past few while, and after many troubleshooting steps, I have finally found the culprit: PlayReady.

![The Cider interface with a pop-up that says Playback Error. A red rectangle is drawn around the error message.](https://user-images.githubusercontent.com/32032824/226325512-cecfa2b8-a476-466a-bf8b-05f208e28d97.png)
*Playback Error message*

#### Problems with PlayReady
* Random but frequent "Playback Error" pop-ups as shown above
  - Media keys (especially resume) doesn't work anymore after the error
* Cider Audio Lab (at least Spatialization) stops working

### Steps to Reproduce

1. Open Settings → Audio
2. Switch "DRM System" from `Default`/`Widevine` to `PlayReady`
3. Restart Cider
4. Play a song (You will hear that Spatialization effects are gone)
5. Try to switch tracks
6. See Playback Error

### Anything else?

\* Ticket \#597: https://discord.com/channels/843954443845238864/1084451147873517608

**Comment by coredev-uk** [comment]
Ticket was closed so ig resolved
