### ISSUE TITLE
[Bug]: "Share..." and "Show in Apple Music" items broken in currently playing song's context menu

### ISSUE THREAD

**Issue by numanumaa** [ciderapp/Sabiiro-BugTracker#104]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

https://discord.com/channels/843954443845238864/905459703092490340/1087474634523426846

### Operating System Version

Windows 11 22H2

### Describe the Bug

In the currently playing song's context menu, attempting to use the "Share..." options don't work and results in a "Failed to share" toast with no clipboard contents. Additionally, the "Show in Apple Music" item doesn't appear to do anything.

https://user-images.githubusercontent.com/79871965/226503734-439192b1-82c9-4cf8-8a70-584bc4520efa.mp4

Oddly, other context menus with "Share..." options copy the appropriate link to the clipboard with an expected "Copied to clipboard" toast.

### Steps to Reproduce

1. Play a song
2. Open the current song's context menu
3. Attempt to use the "Share... / Show in Apple Music" options

**Comment by coredev-uk** [comment]
Resolved in https://github.com/ciderapp/project2/commit/7809b9533452e4a6687346d2c79c216c912ca8c9
