### ISSUE TITLE
[Bug]: Like and Dislike buttons do nothing

### ISSUE THREAD

**Issue by trparky** [ciderapp/Sabiiro-BugTracker#105]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

https://discord.com/channels/843954443845238864/905459703092490340/1087474634523426846

### Operating System Version

Windows 11 v22621.1413

### Describe the Bug

The Like and Dislike buttons do nothing when you right-click on the album artwork of a playing song.

### Steps to Reproduce

1. Start playing a song.
2. Right-click on the album art to the left of the song title and look at the popup menu.
3. Note how the Like and Dislike buttons do nothing, they don't even get a hover effect when you hover your mouse over them.

**Comment by coredev-uk** [comment]
I cannot replicate this in the latest build. Please try the latest build and reopen the issue if it persists.

**Comment by oengelha** [comment]
I am encountering the same issue when playing my personal station.
When I am in a playlist or just play a song the Like/Dislike buttons work normally.

**Comment by coredev-uk** [comment]
Resolved in ciderapp/project2@bc995476196a50e79379d7a172d4f6d67bc4f35a
