### ISSUE TITLE
[Bug]: XML character entities appearing in lyrics

### ISSUE THREAD

**Issue by numanumaa** [ciderapp/Sabiiro-BugTracker#107]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

https://discord.com/channels/843954443845238864/905459703092490340/1087772548609093662

### Operating System Version

Windows 11 22H2

### Describe the Bug

Occasionally XML character entities will appear in lyrics. The most obvious example I can think of is in "Slipknot - Psychosocial," where the characters `<` and `>` appear as `&lt;` and `&gt;` respectively.

![image](https://user-images.githubusercontent.com/79871965/226752566-19ab7719-e15b-4e74-8b8f-ebda337876c3.png)
https://music.apple.com/us/song/psychosocial/926187670

As another example, in "Ho-Kago Tea Time - Go! Go! Maniac," `&` will appear as `&amp;`.

![image](https://user-images.githubusercontent.com/79871965/226753622-438caed7-acd8-40e9-9396-9646ac73b850.png)
https://music.apple.com/us/song/go-go-maniac-from-k-on/367317085

On Apple Music (Android) the lyrics appear as expected.

### Steps to Reproduce

1. Play a song that uses some of XML's special characters within its lyrics (try the above)
2. Review lyrics for the potential issue

**Comment by d3rpp** [comment]
Yep, can reproduce. I think i know where this is coming from but the file that handles lyrics is fucking 1200 lines of wizard magic so idk how to fix

**Comment by d3rpp** [comment]
Tagging @booploops as they wrote the lyrics code

**Comment by booploops** [comment]
fixed in `1d55c3dc29ae18159f8306e9a28707cb7d0f1998`
