### ISSUE TITLE
[Bug]: Window is Transparent

### ISSUE THREAD

**Issue by JimDude7404** [ciderapp/Sabiiro-BugTracker#108]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

https://cdn.discordapp.com/attachments/1050090981808156672/1085403404991463535/Cider_2.0.0_x64_en-US.msi

### Operating System Version

Windows 10 Version 21H2

### Describe the Bug

There is just full transparency without any option to revert to Opaque or add a bit of frosting too it. 

![image](https://user-images.githubusercontent.com/67085206/226926602-987530f2-1123-4906-a2e3-34a8ecf1a4aa.png)

### Steps to Reproduce

1. Just open the app m8

### Anything else?

Not asking for the entire world here. At least add back opaque :)

**Comment by coredev-uk** [comment]
Bug with running Mica on Win10.

**Comment by d3rpp** [comment]
Fixed in latest supporter build (ty booploops)
