### ISSUE TITLE
[Bug]: Immersive mode not fullscreening properly when maximized

### ISSUE THREAD

**Issue by numanumaa** [ciderapp/Sabiiro-BugTracker#111]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

https://discord.com/channels/843954443845238864/905459703092490340/1088332764262174790

### Operating System Version

Windows 11 22H2

### Describe the Bug

When Cider is maximized and in Immersive mode the fullscreen function appears to break. The Windows taskbar remains on screen stripped of information and Cider does not change size.

https://user-images.githubusercontent.com/79871965/227203245-8da04b61-1e38-438d-bf74-b54238979f4b.mp4

### Steps to Reproduce

1. Play a song
2. Ensure Cider is maximized and in Immersive mode
3. Click the fullscreen button

**Comment by coredev-uk** [comment]
This invokes a fullscreen function on both electron and tauri, so that should be enough now.
