### ISSUE TITLE
[Bug]: Song context menu causing page jumping on albums

### ISSUE THREAD

**Issue by numanumaa** [ciderapp/Sabiiro-BugTracker#112]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

https://discord.com/channels/843954443845238864/905459703092490340/1088332764262174790

### Operating System Version

Windows 11 22H2

### Describe the Bug

When opening a song's context menu on an album page and selecting an option, the page tends to jump around. This happens at the beginning and end of an album's tracklist. I couldn't get the same behavior looking at the middle of a tracklist, nor when I used the context menu for albums along the bottom of the page.

It admittedly doesn't make the app unusable in any way but it's pretty jarring.

https://user-images.githubusercontent.com/79871965/227227957-a006ea37-8ec3-417c-aa20-ca1db62b9997.mp4

### Steps to Reproduce

1. Go to an album page
2. Ensure you are near the top or bottom of the tracklist
3. Open a song's context menu in the tracklist
4. Select a context menu option

**Comment by coredev-uk** [comment]
I cannot replicate this in the latest build. Please try the latest build and reopen the issue if it persists.

**Comment by numanumaa** [comment]
Apologies for the late response @coredev-uk, but this issue is still present for me using the current Microsoft Store release (4/24/23) and the prerelease below (4/27/23):
https://discord.com/channels/843954443845238864/905459703092490340/1101229821712928778

I was able to replicate this issue on my laptop which had no previous Cider 2 installation using either build. Both of my PCs use Windows 11 22H2 Build 22621.1265.
