### ISSUE TITLE
[Bug]: Clicking on the title of large album elements doesn't do anything

### ISSUE THREAD

**Issue by numanumaa** [ciderapp/Sabiiro-BugTracker#113]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

https://discord.com/channels/843954443845238864/905459703092490340/1088332764262174790

### Operating System Version

Windows 11 22H2

### Describe the Bug

Attempting to click titles of large album elements doesn't do anything. Expected behavior is going to the album's page.

![image](https://user-images.githubusercontent.com/79871965/227405298-8d6b3840-9475-4590-b364-bcf0d980f18d.png)

### Steps to Reproduce

1. Click on the title of a large album element

**Comment by Monochromish** [comment]
Fixed.
