### ISSUE TITLE
[Bug]: Error with Icon (not really important but still a bug xd)

### ISSUE THREAD

**Issue by benniblot** [ciderapp/Sabiiro-BugTracker#118]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

04.04.2023

### Operating System Version

Windows 11 version 22H2

### Describe the Bug

The Icon of Cider Preview is not being displayed properly (black border and cropping)

### Steps to Reproduce

1. Install the App
2. Search for / open / pin it 
3. Look at the icon

### Anything else?

![image](https://user-images.githubusercontent.com/47495914/229898015-5333deb0-b342-41b1-b778-81be73ae9817.png)
![image](https://user-images.githubusercontent.com/47495914/229898034-0d12be8a-90e4-4359-95e9-81ed5b88886d.png)

### Build timestamp

Built on 03/04/2023, 08:09:30 | Quasar v2.11.2 | Sabiiro

**Comment by coredev-uk** [comment]
no.
