### ISSUE TITLE
[Bug]: 'Problem connecting; there may be a network issue'

### ISSUE THREAD

**Issue by m3inbruder** [ciderapp/Sabiiro-BugTracker#120]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

05.4.2023

### Operating System Version

Windows 11 pro 22h2 22621.1413

### Describe the Bug

I logged in to apple music and was given this error, and none of my music loads. I did get a windows firewall prompt but I gave access to cider so I wouldn't think this would have caused any issues.

I logged in on my laptop just fine, and I am not using a vpn or anything along those lines.

### Steps to Reproduce

I signed out of apple music and signed back in, and once I had entered my 6 digit verification code for my apple account the same error popped up.

**Comment by ez1606** [comment]
I'm running into the same issue with two different devices at home. Tested on two different networks (home, hotspot) and the end result is the same with the latest Cider update. I also remember after the cider app was updated, for some reason I was asked to sign in again, which doesn't make sense to me as I was already signed in prior to the update.

Here's what the error looks like

![image](https://user-images.githubusercontent.com/65985749/230109605-527fc89d-fae3-4f61-b559-9b6539fd314c.png)

**Comment by ez1606** [comment]
For clarity, after problem connecting message comes up, I can access my music. If I restart the app, it goes into a blank screen as seen below. As the issue is reproducible at will, how can we help in gathering logs and understanding what's happening?

![image](https://user-images.githubusercontent.com/65985749/230110546-b108eb1b-2001-4c85-9b70-95132efb4679.png)

**Comment by zneumann1** [comment]
I have the same issue from Microsoft Store release of Cider 2.

Edition	Windows 11 Pro Insider Preview
Version	22H2
Installed on	‎2/‎17/‎2023
OS build	25300.1000
Experience	Windows Feature Experience Pack 1000.25300.1000.0

**Comment by d3rpp** [comment]
This is a known, qwirk

i've always found that when the sign-in fails, it doesn't fail, apple is just dumb

in realty it's logging in just fine, however the 2nd part where it refuses to show up is a known & fixed bug, we're awaiting microsoft store approval
