### ISSUE TITLE
[Bug]: Cider 2.x cannot open after initial launch.

### ISSUE THREAD

**Issue by apippuM** [ciderapp/Sabiiro-BugTracker#123]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

Latest Version

### Operating System Version

Windows 11 22H2 Build 22621.1413

### Describe the Bug

Cider cannot open after initial launch.

I bought Cider 2.x from Microsoft Store, install it the first time, it runs well in few months, I can use it normally without issues until recently,

after closing the app, tried to open again, all I get is just blank screen without even Cider logo startup showing. I literally have no clue what happened, tried to force close from task manager, and open it again, no signs of life

Tried uninstalling and reinstall again, same issue.

### Steps to Reproduce

1. Fresh install from Microsoft Store, runs well on first launch (Account login, play music, etc)
2. I close the app and tried to open again, all I got is blank screen with no cider logo showing at the start
3. Went to app settings to reset and repair the app
4. Works well as I mentioned in the first point, and after closing it and tried to open again, same issue as second point
5. Tried reinstalling from Microsoft Store
6. Works well as I mentioned in the first point, and after closing it and open it again, same issue again as second point
7. Frustrated

### Anything else?

[specs.txt](https://github.com/ciderapp/Sabiiro-BugTracker/files/11180544/specs.txt)

![Screenshot 2023-04-08 015159](https://user-images.githubusercontent.com/62385927/230654817-eeb9824d-35bd-40fd-8cfe-9a93676a678d.png)

**Comment by aabbey33** [comment]
Can confirm. Issue is occurring to me, too. 

If it's any assistance, I noticed that when logging in with my apple credentials, the login window says an error occurred, but cider loads normally in the background.

Could it be that its not saving a session cookie or something, so subsequent reloads of the app causes it to error out, thinking its signed in but apple is rejecting it?

**Comment by cryptofyre** [comment]
This issue has been resolved in the newest hotfix but is awaiting Microsoft approval, closing this issue for the time being.
