### ISSUE TITLE
[Bug]: Turbo Calls Failing on Certain Playlists

### ISSUE THREAD

**Issue by mrhonbon** [ciderapp/Sabiiro-BugTracker#124]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

4/3/2023 2:09:30 AM, v2.11.2

### Operating System Version

Windows 11 22H2

### Describe the Bug

https://user-images.githubusercontent.com/102571374/230693028-65cb9ea9-0783-4017-a73d-5911d5f8536e.mp4

Apple Music Curated playlists don't load but my playlists do.

### Steps to Reproduce

1. Clicked on my playlist
2. Clicked on any Apple Music Curated playlist from any page

### Build timestamp

1680911194778

**Comment by coredev-uk** [comment]
The issue doesn't seem to be with Apple Music Curated playlists as a whole, just certain ones.

**Comment by coredev-uk** [comment]
The only curated playlist that I've found that has this error is with the one you show in the video, Rap Life. All other playlists load correctly from my testing.

**Comment by coredev-uk** [comment]
Think https://github.com/ciderapp/project2/commit/af959918f2b6997f1b3be31ef224f845b87dafe2 has fixed this issue. If you find another playlist that fails to load, please make a new issue.
