### ISSUE TITLE
[Bug]: Cider reporting wrong bitrate

### ISSUE THREAD

**Issue by n1ckybleedem** [ciderapp/Sabiiro-BugTracker#130]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

Latest Microsoft Build

### Operating System Version

Windows 11 22H2

### Describe the Bug

Cider reporting 256kbps even when the music kit is playing a 64kbps file

### Steps to Reproduce

1. Play a playlist and wait until the music kit decides to feed you 64kbps
2. Check the bitrate badge and it will show 256kbps

### Anything else?

![Cider_JG86HchdTH](https://user-images.githubusercontent.com/55335959/230983672-c29611b1-cd42-4b60-b2f1-646d4a1b81b4.png)

**Comment by coredev-uk** [comment]
The badge is displayed based off the bitrate from the current MusicKit instance. Can be obtained with `MusicKit.getInstance().bitrate`, we don't actively check the current bitrate of the audio stream.

**Comment by cryptofyre** [comment]
Can be done easily by comparing the flavor.

**Comment by coredev-uk** [comment]
done
