### ISSUE TITLE
[Bug]: MiniPlayer does not open album

### ISSUE THREAD

**Issue by MathiAs2Pique** [ciderapp/Sabiiro-BugTracker#132]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

03/04/2023 08:09:30

### Operating System Version

Windows 10 Pro version 21H2

### Describe the Bug

Albums don't load. Before the Windows Store update, all you had to do was click on an album to see it, but now a loading icon quickly appears, then nothing, just a black screen.

### Steps to Reproduce

1. Play any song
2. Click on the album in the mini player (bottom left)
3. The bug

Or more generally, just go to an album, regardless where you find it, and you (I, at least) will encounter the bug

### Build timestamp

1681397614046

**Comment by coredev-uk** [comment]
I believe this is down to the app not handling the album link in the miniplayer state. I think its still linking in the app, just not collapsing the miniplayer accordingly.

**Comment by MathiAs2Pique** [comment]
Hi, 
It was not only happening on the mini player / immersive player, but everywhere, even after an application restart.
I don't really know how and why, but the problem has been solved for me this evening.

Idk if it was on purpose, but thank you anyways !

**Comment by coredev-uk** [comment]
Appears to be resolved in recent builds.
