### ISSUE TITLE
[Bug]: Shuffle/play only adds a few amount of songs from my library to the queue

### ISSUE THREAD

**Issue by emilianorobles** [ciderapp/Sabiiro-BugTracker#134]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

4/10/2023, 12:49:51 PM CST | Quasar v2.11.2

### Operating System Version

Windows 11 Pro 22H2

### Describe the Bug

If I shuffle or play songs from my Songs library, Cider will only add to the queue the ones close to the one I played.
Example: I sort my songs library by Name in Descending order, if I play a song that starts with 'A', Cider will only add songs from the letter 'A' and some 'B' to the queue, it doesn't load songs deeper on my library.

### Steps to Reproduce

Open the Songs library, play any song and check the queue.

**Comment by coredev-uk** [comment]
Cannot reproduce this in recent builds, will assume its resolved.
