### ISSUE TITLE
[Bug]:  Shuffle Songs not Working

### ISSUE THREAD

**Issue by Zennik** [ciderapp/Sabiiro-BugTracker#137]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

Cider is on its latest build

### Operating System Version

Windows 11 21H2

### Describe the Bug

The "randomize" button doesn't work, it only plays songs that are close to each other.

### Steps to Reproduce

Just tap on the randomize button while listening songs from the "Songs" album

**Comment by coredev-uk** [comment]
Cannot reproduce this in recent builds, will assume its resolved.
