### ISSUE TITLE
[Bug]: Sorting on Albums page always resets

### ISSUE THREAD

**Issue by iamruletik** [ciderapp/Sabiiro-BugTracker#138]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

Built on 4/11/2023, Quasar v2.11.2, Downloaded via Microsoft Store

### Operating System Version

Windows 11 Pro 22H2, OS Build 22621.1555

### Describe the Bug

![image](https://user-images.githubusercontent.com/61237389/232001206-bc55f13d-1929-4fad-9af5-18f7cf379471.png)
If you look at the screenshot, you will see that in the sorting menu, I chose "Date Created" earlier. However, whenever I leave the Albums page, it resets to default sorting visually. Additionally, if, for example, I'm listening to an album from way down below, the app doesn't scroll to the place where I've been.

### Steps to Reproduce

1. Open Albums page
2. Choose sorting type
3. Leave albums page to any other page

**Comment by coredev-uk** [comment]
Resolved as of https://github.com/ciderapp/project2/commit/ffe3b1f0393c520b01e4332994ba9debcdc66f0c
