### ISSUE TITLE
[Bug]: Explicit songs won't play

### ISSUE THREAD

**Issue by Pizzamouserat** [ciderapp/Sabiiro-BugTracker#140]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

Built on 4/10/2023, 2:49:51 PM | Quasar v2.11.2 | Sabiiro

### Operating System Version

Windows 11 22H2

### Describe the Bug

Unable to play any explicit songs even with apple restrictions set to"explicit". I have toggled this on/off a few times without any changes.

![image](https://user-images.githubusercontent.com/130812015/232179672-73166ffc-f2ac-4f12-a058-edab064a8800.png)

### Steps to Reproduce

1. Unable to play any songs with an "E" noted next to it
2. Skips over explicit songs in queue
3. Restarted/re-installed app without any changes

**Comment by coredev-uk** [comment]
Does it allow you to play music on [AM Web](https://beta.music.apple.com)?

**Comment by Pizzamouserat** [comment]
It allows me to play explicit(E) songs on AM web and on the legacy version of Cider but not the current version. 

I un-installed/re-installed and the issue remains unfortunately.

I do notice upon signing into the the current version of Cider I get the attached error before it allows me into the application. Once I enter my email/password it gives me that error before 2FA has a chance to work. But ultimately it signs me in so I am unsure if this is related or not.

![image](https://user-images.githubusercontent.com/130812015/232640021-7d804300-19bb-4e45-b6b6-6a09c50bf3bb.png)

**Comment by coredev-uk** [comment]
It seems a fix has already been made. If you acquired the app from the releases made on Discord, you can get the latest one from there, if you installed from MS Store, I'm not entirely sure when a release (or if a release has already been made). I suggest updating to the latest version in any case.
