### ISSUE TITLE
[Bug]: Latest Release is duplicated on artist pages

### ISSUE THREAD

**Issue by cephalopodd** [ciderapp/Sabiiro-BugTracker#142]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

10/04/2023 dd/mm/yyyy

### Operating System Version

Windows 11 25336.1000

### Describe the Bug

As said in title

### Steps to Reproduce

1. Go to any artist page
2. scroll???

### Anything else?

![delete](https://user-images.githubusercontent.com/97368781/232603449-976ac5f4-97d7-4363-8331-8035deb59da2.png)

**Comment by coredev-uk** [comment]
Resolved with https://github.com/ciderapp/project2/commit/37c88af5ddbdc50c94f08f7d5b3ef28b56de71eb
