### ISSUE TITLE
[Bug]: Music Video's not working with RPC

### ISSUE THREAD

**Issue by Celarye** [ciderapp/Sabiiro-BugTracker#143]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

Quasar v2.11.2 | Sabiiro

### Operating System Version

Windows 11 Insider latest dev build

### Describe the Bug

When playing a music video in Cider 2, Discord Rich Presence shows blank.

### Steps to Reproduce

1. Make sure you have Discord Rich Presence turned on in the Cider 2 settings and Discord is launched.
2. Play a music video in Cider 2.

### Build timestamp

Built on 10/4/2023, 20:49:51

**Comment by coredev-uk** [comment]
Cannot reproduce this in recent builds, will assume its resolved.
