### ISSUE TITLE
[Bug]: Terrible Sound With Dolby Atmos

### ISSUE THREAD

**Issue by Oluwademiladeak** [ciderapp/Sabiiro-BugTracker#145]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

1.1.2.0

### Operating System Version

Windows 11 Pro Build 22621.1555

### Describe the Bug

I use Dolby Atmos on my PC, and it works perfectly with my laptop speakers and apps, except with Cider.

This entire time I thought Cider had terrible audio quality, but I did some troubleshooting and found out Cider and Dolby Atmos don't go well together. When I have DA enabled, Cider sounds so flat and low quality.

### Steps to Reproduce

1. Play a track on Cider
2. If your laptop comes with DA, turn it on while the track is playing and notice the change. If you don't have DA like me, install the Dolby Access app from the Microsoft store, set it up, go to your sound settings and set Spatial Audio to "Dolby Atmos for Headphones"

### Anything else?

Nothing

### Connect Device ID

5seiQlbS4BsI0hlJ9TdJ

**Comment by yazninja** [comment]
hi, my laptop comes with DA and for me it enhances the audio quality actually, well not techincally enhances in paper, but it does sound fuller... Which app do you have (not the access app) for Dolby Audio?

**Comment by Oluwademiladeak** [comment]
It sounds fine with headphones in, but when I'm playing through my laptop speakers, it sounds awful.

I use the Dolby Access App though.

**Comment by yazninja** [comment]
https://user-images.githubusercontent.com/71800112/233837502-e7ab6b68-8a79-4bb7-bfa1-b75bb03ae1f7.mp4

do you find the DA on here as bad audio?

**Comment by Oluwademiladeak** [comment]
Nope. This sounds fine.

**Comment by yazninja** [comment]
> Nope. This sounds fine.

it might be a device driver issue then, because i had this video on lossless so mp4 shouldnt compress anyth and it gets direct audio, maybe try setting  your spatial audio to off and back to dolby atmos?

**Comment by Oluwademiladeak** [comment]
Yeah, just found out it also happens with Windows Sonic.
