### ISSUE TITLE
[Bug]: Search filtering between Apple Music/Library doesn't work properly

### ISSUE THREAD

**Issue by mpar-22** [ciderapp/Sabiiro-BugTracker#146]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

https://discord.com/channels/843954443845238864/905459703092490340/1098193423028191244

### Operating System Version

Windows 11 22H2

### Describe the Bug

When using the search bar (whether it's the top widget or a button), selecting between the apple music and library filters doesn't apply. It always searches Apple Music's servers regardless if library filtering is selected or not. 

### Steps to Reproduce

1. Clicked the search bar
2. Set filter to Library
3. Searched
4. Results came from Apple Music instead of Library

**Comment by coredev-uk** [comment]
Fix has been made with https://github.com/ciderapp/project2/commit/371911075b0d0bd633589b0fbd17edbf29b6cd40
