### ISSUE TITLE
[Bug]: Window position resets/random at launch

### ISSUE THREAD

**Issue by timotyturini** [ciderapp/Sabiiro-BugTracker#148]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

21/04/2023 (Built on 10/04/2023)

### Operating System Version

Windows 11 22H2 (22621.1555)

### Describe the Bug

The app won't remember the last window position after closing it.

### Steps to Reproduce

1. Launch the app
2. The app window will show in a random position

### Anything else?

Seems to choose an arbitrary random position, but always on the main monitor.
In my case, i have a two monitor setup (2 x 2560x1440p).

**Comment by coredev-uk** [comment]
Gonna link this in to #139.
