### ISSUE TITLE
[Bug]: Localization (?) text shown in UI

### ISSUE THREAD

**Issue by paytontech** [ciderapp/Sabiiro-BugTracker#149]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

`Built on 4/10/2023, 2:49:41 PM`

### Operating System Version

Windows 11 build 25336

### Describe the Bug

Pressing the menu icon in the top left of the sidebar, the sign out text in the Apple Music tab says "menubar.options.signout" rather than just "Sign Out". Definitely a super minor issue (not even really a bug) but something I noticed was strange.

### Steps to Reproduce

1. Open menu bar
2. Go to Apple Music tab
3. That is it.

### Anything else?

![image](https://user-images.githubusercontent.com/81662879/233813924-c9e6fcbf-5fec-48d1-8e45-a5898511df75.png)
![image](https://user-images.githubusercontent.com/81662879/233813928-49cd8253-5916-4bb8-838e-d2271b6bdbdc.png)

**Comment by coredev-uk** [comment]
This is an outdated build compared to the latest donator build. I'm guessing this is from the Microsoft Store, with that you will just need to wait until the next update.
