### ISSUE TITLE
[Bug]: Unable to see text by default

### ISSUE THREAD

**Issue by JimDude7404** [ciderapp/Sabiiro-BugTracker#15]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Operating System Version

WIndows 10 21H2

### Describe the Bug

![image](https://user-images.githubusercontent.com/67085206/223311168-c561e770-c4cc-447d-9ef7-ee43bce787a5.png)
The text on the side is unreadable. Maybe fix it by using frosted acrylic

### Steps to Reproduce

1. Open the app with something white behind it
2. Thats it

**Comment by JimDude7404** [comment]
I would just add a darker tint behind it and your good. It should be really easy since you already have it setup so that you can have it change based on song theme.

**Comment by JimDude7404** [comment]
Reopen it please!

**Comment by d3rpp** [comment]
I'll just remove transparency effects from Win 10

todo: test Sabiiro Commit 399aebfc8af23850a0b0abb0952790db472b3f5a
