### ISSUE TITLE
[Bug]: Language problems.

### ISSUE THREAD

**Issue by yunusemredincell** [ciderapp/Sabiiro-BugTracker#150]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

20/04/23

### Operating System Version

Windows 10

### Describe the Bug

Today , I started using Cider from Windows10. When I choose language Turkish, all operations are not Turkish. There are two language on my Cider.  I attached screenshot about my issue. 
![Ekran Görüntüsü (163)](https://user-images.githubusercontent.com/120384533/233832415-91529567-a03b-443e-8afd-28907043048c.png)

### Steps to Reproduce

I changed language and I saw this bug :)

**Comment by coredev-uk** [comment]
Various settings in the application are not fully translated / have a translation added yet. As the interface is not final, many settings will not be translated as it could be removed. You can contribute to Cider translations [here](https://translate.cider.sh).
