### ISSUE TITLE
[Bug]: Replay 2023 is NaN

### ISSUE THREAD

**Issue by UnbreakCode** [ciderapp/Sabiiro-BugTracker#152]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

2.0.1 / latest

### Operating System Version

Windows 10

### Describe the Bug

Replay 2023 does not show Total Minutes, Total Albums, Total Artists, Total Songs
![image](https://user-images.githubusercontent.com/34512773/233994773-ac803626-97e4-4e7b-ad89-d0439e601a0d.png)

Description: 
Cider2 currently uses `https://amp-api.music.apple.com/v1/me/music-summaries/year-2023?extend=inLibrary&views=top-artists,top-albums,top-songs&include[music-summaries]=playlist&include[playlists]=tracks&includeOnly=playlist,tracks,song,artist,album` as API endpoint that no longer has uniqueSongCount, uniquePlaylistCount..

Fix: 
To get this infos again a new endpoint is needed: `https://amp-api.music.apple.com/v1/me/music-summaries/milestones?ids=year-2023&l=de-de&omit[resource]=autos&include[music-summaries-milestones]=top-artists,top-songs,top-albums&fields[songs]=name,artwork&fields[artists]=name,artwork&fields[albums]=name,artwork`

Using this endpoint you can get listenTimeInMinutes and so on: 
![image](https://user-images.githubusercontent.com/34512773/233996013-3e7d237a-4e61-4a63-9c06-d4dc4fcacc07.png)

### Steps to Reproduce

Open Replay 2023

**Comment by coredev-uk** [comment]
The use of milestones is being looked into, however the data that the api provides from this, will not provide an exact amount of current listening time, from my testing it will provide the 5000, 7500, 10000 and others. With this I'm not entirely sure if the highest figure will even give a reliable figure.

**Comment by UnbreakCode** [comment]
That's true, but I haven't found where else to get the data from. However, I believe that the listeningTimeInMinutes, for example, will be relatively accurate.In Cider 1, hours were also rounded up or down so maybe that's not 100% needed.

**Comment by coredev-uk** [comment]
I made a patch to include milestone data and the time in minutes from the max value. Hope this should be enough.
