### ISSUE TITLE
[Bug]: Mini Player does not remain in foreground

### ISSUE THREAD

**Issue by vaoagost** [ciderapp/Sabiiro-BugTracker#154]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [x] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

24/04/2023

### Operating System Version

Windows 11

### Describe the Bug

When using the Mini Player, the application should remain in the foreground but sometimes it is pushed to the background when another application is opened on the same screen, causing the player to be overlaid.

I tested the previous version of Cider and found that it consistently remained in the foreground, regardless of which other applications were open.

### Steps to Reproduce

When selecting the "mini-player" functionality

**Comment by coredev-uk** [comment]
A method to make the window pinned needs to be done on the backend. @d3rpp

**Comment by d3rpp** [comment]
tf you mean pinned?

**Comment by d3rpp** [comment]
aight sorted, just awaiting an answer one detail from booploops and i'll push it up

thanks for this one, i don't use the miniplayer so i didn't notice it lol

**Comment by d3rpp** [comment]
cool, pushed
