### ISSUE TITLE
[Bug]: Songs are not added to playlist

### ISSUE THREAD

**Issue by eightydegrees** [ciderapp/Sabiiro-BugTracker#159]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

https://discord.com/channels/843954443845238864/1092593196862808084/1099074744273338488

### Operating System Version

Windows 11 22H2

### Describe the Bug

Trying to add songs to a playlist doesn't add them at all, does leave an error in the devtools console. (lemme know if any of this is sensitive information)
![image](https://user-images.githubusercontent.com/47302735/234627243-ff4938b6-e43c-4dfb-84e4-88488e510a9a.png)

### Steps to Reproduce

1. Right click a song
2. Add to a playlist

**Comment by coredev-uk** [comment]
Aware of this issue, was resolved with https://github.com/ciderapp/project2/commit/f3ad235a78ed6c4eefa5d625fa11c260d7b6af5a

This patch will be in the next donator build.
