### ISSUE TITLE
[Bug]: Like/Dislike buttons non-functional

### ISSUE THREAD

**Issue by adamtee** [ciderapp/Sabiiro-BugTracker#161]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

25/04/2023, 9:28:53 AM | Quasar v2.11.20 | Sabiiro

### Operating System Version

Windows 11 Home 22621.1635

### Describe the Bug

When playing music, I am unable to right click on the song and select that I love or dislike the song

### Steps to Reproduce

When right clicking on the playing song, unable to click the LOVE or DON'T LIKE buttons
![2023-04-28 19_09_06-Cider 2](https://user-images.githubusercontent.com/33622448/235106919-3e02cb0c-63b3-49db-931c-6cfb95d88f50.png)

### Anything else?

Right click on playing song in bottom left of app, try and click HEART or DOWN THUMB

### Connect Device ID

8e8b4c79ca2bcdfdadcfec74b5e5fac8b2a8ca45

### Build timestamp

25/04/2023, 9:28:53 AM | Quasar v2.11.20 | Sabiiro

**Comment by coredev-uk** [comment]
Resolved with ciderapp/project2@17ee4fd7d53332aff576162d52f9879630c9b7d2
