### ISSUE TITLE
[Bug]: "Songs" doesn't save the "Sort By" option

### ISSUE THREAD

**Issue by onealhtml** [ciderapp/Sabiiro-BugTracker#162]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

Built on 4/24/2023, 8:28:53 PM I Quasar v2.11.10 I Sabiiro 8e8b4c79ca2bcdfdadcfec74b5e5fac8b2a8ca45

### Operating System Version

Windows 11 Pro 22H2 22621.1635

### Describe the Bug

Everytime I go to "Songs", it doesn't save the last "Sort by" option, it seems the options to be save, but the music order is not the same as the option.

### Steps to Reproduce

https://user-images.githubusercontent.com/97130234/235321200-c3423925-f996-4a30-83e8-b7569744f017.mp4

### Connect Device ID

dVm2HKZJfhBcn9JklKTu

### Build timestamp

1682796251980

**Comment by coredev-uk** [comment]
Resolved in latest build. Please await an update on windows store.
