### ISSUE TITLE
[Bug]: Pinned Playlists Icons not loading

### ISSUE THREAD

**Issue by svalencia014** [ciderapp/Sabiiro-BugTracker#163]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

MS Store Install; v2.0.1

### Operating System Version

Windows 11

### Describe the Bug

On the pinned playlists section on the home page, the icon of the playlist is not loading.

The playlist does have an icon as shown here: 
![image](https://user-images.githubusercontent.com/68522351/235331164-5e1000fe-0cc8-45e8-93f6-a8429dca36c0.png)

This is what shows on the home page:
![image](https://user-images.githubusercontent.com/68522351/235331187-79472750-2a16-4bf3-a640-208eb99ccd99.png)

### Steps to Reproduce

1. Create a Playlist
2. Pin that playlist to the home page (More -> Pin to home)
3. Go to the home page

### Connect Device ID

AF0sBmLQTNu6R6kJhYxD

### Build timestamp

1682817875539

**Comment by svalencia014** [comment]
The same thing happens when in Card mode instead of List Mode
![image](https://user-images.githubusercontent.com/68522351/235449406-cf27682d-3422-43f1-9904-16b0a0d6801e.png)

**Comment by svalencia014** [comment]
It appears to have fixed itself so far after updating to 2.0.2.

**Comment by coredev-uk** [comment]
A partial fix was put in, further work will be made in the future
