### ISSUE TITLE
[Bug]: Unable to select "Love" or "Dislike" for songs playing from station

### ISSUE THREAD

**Issue by Wmorg97** [ciderapp/Sabiiro-BugTracker#164]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

Version 2.0.1

### Operating System Version

Windows 11 Version 10.0.22621 Build 22621

### Describe the Bug

When I right-click a song to see the context menu playing from a station, the "Love" and "Dislike" options are not selectable.

### Steps to Reproduce

Generally appears when I right click a song that is playing from a station, such as "[My Name's] station."  Usually when I select a song playing from my library at least the "Love" option is selectable, although sometimes "Dislike" is still not selectable.  It is inconsistent to reproduce.

### Anything else?

![image](https://user-images.githubusercontent.com/66193807/235331999-157ee363-d73b-49c7-b08a-45e160c1c67e.png)

### Build timestamp

1682820010279

**Comment by DuckyBlender** [comment]
same issue here

**Comment by tielqt** [comment]
Confirming this issue on my machine as well.

**Comment by agrmohit** [comment]
The issue is present on my side too

**Comment by theironraiden** [comment]
Having the same Issue on every song, radio or library. On library songs, only the "remove" icon is shown. On radio songs, only the "add" icon is shown.
![image](https://github.com/ciderapp/Cider-2/assets/34741276/8591dbca-a13d-4f5e-893d-ec501f92687a)

**Comment by coredev-uk** [comment]
This is a known bug for older versions. It is resolved within 2.1.1.
