### ISSUE TITLE
[Bug]: Song Shuffle Button Does nothing

### ISSUE THREAD

**Issue by NathanielH-snek** [ciderapp/Sabiiro-BugTracker#166]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Ubuntu

### Build Details

2.0.2.20230427.11

### Operating System Version

Ubuntu 22.04.2 LTS

### Describe the Bug

Clicking the shuffle songs button in the songs section of library does not do anything. Work around is currently clicking a song in the library and then making the queue shuffle. No error messages are produced

### Steps to Reproduce

Click songs
Click shuffle
Nothing happens

**Comment by coredev-uk** [comment]
Appears to be resolved in latest commit.
