### ISSUE TITLE
[Bug]: Song sorting not saved during navigation

### ISSUE THREAD

**Issue by LeadOn** [ciderapp/Sabiiro-BugTracker#169]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

Built on 4/25/2023 1:28:53 AM

### Operating System Version

Windows 11 Pro 22H2 22621.1555

### Describe the Bug

When navigating / launching the app, even if the sorting option is correctly pre-selected (for example : date added/descending), items are not. You need to manually click on the elements to sort again

### Steps to Reproduce

Sort by Date Added / Descending

Try closing / reopening the app or even navigating to a different page and going back to the song library

### Anything else?

Thank you for your hard work!

### Connect Device ID

cVziDX7eTZzfLJ2q7k3i

### Build timestamp

1682976483651

**Comment by coredev-uk** [comment]
Sorting is stored depending on item, so for playlists in your library it will be saved so all playlists will have the same sorting you applied previously. Same applies for library elements (song list, artists and recently added), but normal albums/playlists (non-library) don't have any preserved order to present the album/playlist in the way its supposed to.
