### ISSUE TITLE
[Bug]: Can't sign-in / Sign-in window blank / MusicKit Error / whatever else

### ISSUE THREAD

**Issue by maxwiseman** [ciderapp/Sabiiro-BugTracker#170]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

V2.0.1

### Operating System Version

Windows 11 Pro 22H2 (build 22621.1555)

### Describe the Bug

I just downloaded the update for Cider and was required to log in again, but the issue is that when I click sign in, it just opens about:blank. I have tried restarting my PC, reinstalling the app, clicking reset in the app's page in Windows Settings, repairing the app, etc. It seems like the reset button in Windows settings doesn't do much because even after clicking it, I am still signed into Cider Connect. I tried Cider V1 and it still works fine, but the new one does not. 

### Steps to Reproduce

Click on sign in

### Anything else?

https://user-images.githubusercontent.com/60909484/235550682-725da4bf-6afa-4556-bfd9-3ec812117cf9.mp4

### Build timestamp

4/24/2023

**Comment by tielqt** [comment]
Confirming this issue is also present on my machine. Win11, Microsoft Store version of Cider

**Comment by ty-rehsif** [comment]
same issue same details as the above

**Comment by coredev-uk** [comment]
https://twitter.com/usecider/status/1653114998858604572?s=61&t=rtAEmGKM8YhRHYzWTD0Zgw
