### ISSUE TITLE
[Bug]:

### ISSUE THREAD

**Issue by Chonk3140** [ciderapp/Sabiiro-BugTracker#177]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

A week ago

### Operating System Version

Windows 10

### Describe the Bug

The app signed me out and when i go to login it sends me to a white screen that dosent load anything and when i click to delete it, it just opens a new one up after

### Steps to Reproduce

1. after it signs you out click on sign in
2. it will begin repeating the white screen

### Connect Device ID

LkWmoFCiucNUDAhrliR9

### Build timestamp

1683087665258

**Comment by mpar-22** [comment]
https://twitter.com/usecider/status/1653114998858604572?s=61&t=rtAEmGKM8YhRHYzWTD0Zgw

**Comment by coredev-uk** [comment]
Its pinned...
https://github.com/ciderapp/Sabiiro-BugTracker/issues/170
