### ISSUE TITLE
[Bug]: When in-app volume is at 100% music becomes distorted, but when at lower levels sounds great.

### ISSUE THREAD

**Issue by adub0808** [ciderapp/Sabiiro-BugTracker#178]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

Version 2.02

### Operating System Version

Windows 11 Home 22621.1635

### Describe the Bug

When the in-app volume is set to 100% the audio quality becomes very distorted as if my headphones/speakers were playing at 100% volume but were not. The Cider Audio Lab did not fix anything at all but as soon as I turned down thein-app volume and increased my system volume it sounded great. Please fix this and adjust the volume control in-app to limit distortion. Or, have the in-app volume sync with the system volume. 

### Steps to Reproduce

1. Turned in-app volume to 100%
2. Played music with deeper voice and heavier bass with Sony WH-1000XM4 headphones even at 20% volume and sounded distorted

### Anything else?

[https://www.reddit.com/r/AppleMusic/comments/v0gojb/cider_alpha_app_sounds_horrible_for_some_reason/](url)

### Connect Device ID

Version 2.0.2

**Comment by coredev-uk** [comment]
Just don't put it to 100 in-app. This is probably an issue with MusicKit. If you are after higher volume audio, I suggest turning up the system sound instead.

**Comment by maikirakiwi** [comment]
fixed in latest prerelease
