### ISSUE TITLE
[Bug]: Toggling to Library Search then back to Apple Music breaks things

### ISSUE THREAD

**Issue by mpar-22** [ciderapp/Sabiiro-BugTracker#181]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

https://discord.com/channels/843954443845238864/1050090981808156672/1103440370244788294

### Operating System Version

Windows 11 22H2

### Describe the Bug

When searching (with the top widget being the search bar), thinks break when switching to library search and then back to Apple Music. Namely, search suggestions no longer appear, and hitting enter doesn't end up searching anything; instead, you have to click the search icon in the search bar. 

### Steps to Reproduce

1. Clicked on search bar
2. Switched to library search
3. Searched up an artist and hit enter
4. Clicked on the artist's page
5. Navigated back to the main search menu
6. Switched back to Apple Music search
7. Tried searching again
8. No suggestions popped up, and hitting enter didn't do anything

### Build timestamp

1683158987099

**Comment by coredev-uk** [comment]
Unfortunately search suggestions don't cover library-only items, this is why the suggestions are disabled when you select Library. If you are after music only from your library simple press enter whilst searching and it will display the relevant information.
