### ISSUE TITLE
[Bug]: Pressing the X button in the search box on the Songs page doesn't clear search results

### ISSUE THREAD

**Issue by trparky** [ciderapp/Sabiiro-BugTracker#183]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

Windows Store version (Built on 5/2/2023, PM I Quasar v2.11.1e I Sabiiro | cd304ef210f9e99118f9c783d150844bd82c13f2)

### Operating System Version

Windows 11 22H2, 22621.1635

### Describe the Bug

Pressing the X button in the search box on the Songs page doesn't clear search results.

### Steps to Reproduce

1. Go to the Songs page.
2. Go the search box, type something in.
3. Click the X icon in the search box.
4. Note how it doesn't do anything.

**Comment by coredev-uk** [comment]
Appears to be working as intended on latest commit. Feel free to reopen if it persists.
