### ISSUE TITLE
[Bug]: Immersive/Fullscreen Mode Issue

### ISSUE THREAD

**Issue by vishhhh999** [ciderapp/Sabiiro-BugTracker#185]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

Version 2.0.2 - Sabiiro, Installed 05 May 2023

### Operating System Version

Windows 11 Version 22H2

### Describe the Bug

When opening fullscreen mode, the windows taskbar area greys out and when I come out of fullscreen mode, the taskbar is still greyed out without any icons. And I'd have to click the minimize-maximize buttons on the top right, then it goes into a small window, like around 1/4th of the screen and I'd have to maximize it again to get full-windowed mode.

### Steps to Reproduce

1.Open Cider
2. Play a song
3. Go to immersive mode
4. Go to Fullscreen mode (top left)

### Anything else?

![image](https://user-images.githubusercontent.com/132681076/236481626-ddefc763-7b46-4c78-b612-63bed41c4f6b.png)

### Build timestamp

Built on 5/2/2023, 9:30:53 PM

**Comment by codyisland** [comment]
Try pressing the three dots on the top left. Press dev-test. Then click unsetFS.

**Comment by coredev-uk** [comment]
Duplicate of #155
