### ISSUE TITLE
[Bug]:【最近添加】页面出现空白

### ISSUE THREAD

**Issue by grafce** [ciderapp/Sabiiro-BugTracker#189]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

2023.5.6

### Operating System Version

Windows11 22H2

### Describe the Bug

详细看图片
![029GD` ~581)RR0}5QJQW%5](https://user-images.githubusercontent.com/69634246/236661139-f54ee443-fc54-4714-8b3e-dc054993699b.png)
![CGQM79Z$CT50 4UFPSPZ84S](https://user-images.githubusercontent.com/69634246/236661143-f858ed14-7c63-4cb1-a923-0abc6118103a.png)

### Steps to Reproduce

一点击进去就有这个问题

### Connect Device ID

2.02

**Comment by coredev-uk** [comment]
Please submit issues in English.
