### ISSUE TITLE
[Bug]: Adding a duplicate song to a playlist doesn't warn you

### ISSUE THREAD

**Issue by TreehouseFalcon** [ciderapp/Sabiiro-BugTracker#19]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Operating System Version

Windows 11 22H2

## Current behavior

Adding a song to a playlist that already appears in that playlist doesn't warn you about the duplicate status. This was a feature in Cider 1.x.

## Expected behavior

There should be some sort of popup confirming that you want to add the duplicate song like there is on the Apple Music mobile client.

### Steps to Reproduce

1. Right click a song
2. Hover over "Add to playlist"
3. Select a playlist with hundreds of songs
4. Repeat 1-3 for the same song and playlist
6. There is no warning about the selected song already existing in that playlist

**Comment by Swiftzerr** [comment]
Done in latest commit, thanks for suggesting!

**Comment by TreehouseFalcon** [comment]
This seems to still be present on the latest clientdb build. Updated repro steps to ensure reproduction.

**Comment by Swiftzerr** [comment]
Are you sure you are on the latest version? This is what happens when I try to add a duplicate song:

<img width="461" alt="Screenshot 2023-03-14 at 7 46 28 AM" src="https://user-images.githubusercontent.com/67812203/225038290-a3777846-ca5b-42e4-80ae-de8ce1d55e9b.png">

**Comment by coredev-uk** [comment]
It seems dismissing the dialog causes the songs to still be added. For some reason dismissing calls the cancel function as well as dismiss, not sure why they designed it this way. So, we can either force the user to select an option or find another option for the dialog.

**Comment by coredev-uk** [comment]
Resolved with https://github.com/ciderapp/project2/commit/2265fb3301255cb1d6475ab6d7a278a1d71b6416
