### ISSUE TITLE
[Bug]: Sorting order of playlists is set for everything now instead of single playlist only.

### ISSUE THREAD

**Issue by DeN-AlB** [ciderapp/Sabiiro-BugTracker#195]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

Built on 2.5.2023, 18:00:53 | Quasar v2.11.10 | Sabiiro

### Operating System Version

Windows 11 Pro 22H2 build 22621.1702

### Describe the Bug

After creating the following issue in April, this is solved now.
https://github.com/ciderapp/Sabiiro-BugTracker/issues/128

When sorting a playlist now this sorting is set for everything no matter if playlist or album. It would be great if sorting would be saved for the specific playlist or album only. 

### Steps to Reproduce

Open a playlist and set the sorting to "None" and "Descending".

![grafik](https://github.com/ciderapp/Sabiiro-BugTracker/assets/55697152/062ce669-b4a0-42d3-887c-365d514fa15b)

Now open an album, and you could see that tracks are sorted descending, although you didn't sort it like that.

![grafik](https://github.com/ciderapp/Sabiiro-BugTracker/assets/55697152/95ea2176-e345-4cc1-bc4b-516c7f0192ca)

![grafik](https://github.com/ciderapp/Sabiiro-BugTracker/assets/55697152/9087ef72-545e-46e6-8a4d-36bdf8ac9dcd)

### Build timestamp

1683896557517

**Comment by DeN-AlB** [comment]
Just to let you know that this is still an issue with the new build.

_Built on 17.5.2023, 07:25:48 | Quasar v2.11.10 | Sabiiro_

**Comment by coredev-uk** [comment]
People keep picking and choosing whether or not they want this feature. Currently, the sorting option for library items (Playlists, Songs, Artists and Albums) is saved to settings. We are not planning on changing this again, if the community came to a consensus on this then it may be changed, but until then, we're leaving it.
