### ISSUE TITLE
[Bug]: Unable to add song to playlist created in Cider

### ISSUE THREAD

**Issue by nxahjs** [ciderapp/Sabiiro-BugTracker#201]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

Cider v2.0.2

### Operating System Version

Windows 11 22H2 (25357.1)

### Describe the Bug

Attempting to add songs to a newly created playlist results in an endless spinning loading circle in the top right of the application window. Songs never actually end up getting added to the playlist

### Steps to Reproduce

1. Click create new in the playlists section of the left-hand column
2. Create a new playlist
3. Play a song
4. Right click song artwork in the bottom left
5. Select add to playlist, and try to add to your new playlist

### Anything else?

![image](https://github.com/ciderapp/Sabiiro-BugTracker/assets/38191751/6d915874-33fb-4a90-b9ec-58f8af12998a)
Console error when adding song to playlist

### Connect Device ID

9Vp4mDAnPhKoBmy5kKu1

### Build timestamp

1684171858114

**Comment by coredev-uk** [comment]
I believe this issue has since been fixed. From my testing it works as intended. Update your client to the latest version, if the issue persists, let me know.
