### ISSUE TITLE
No offline download[Bug]: 

### ISSUE THREAD

**Issue by elprofefrancis** [ciderapp/Sabiiro-BugTracker#203]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

Today

### Operating System Version

Windows 11

### Describe the Bug

Offline download is the reason I bought this app.  Everything else looks incredible, just wondered if this feature is in the works?

### Steps to Reproduce

Offline download is the reason I bought this app.  Everything else looks incredible, just wondered if this feature is in the works?

**Comment by Mrman1093** [comment]
To my knowledge, Apple's MusicKit doesn't support offline downloads. Maybe in the future, if Apple ever enables it, offline downloads will become available in Cider. If you are looking for offline playback through Apple Music you can use iTunes or the new Apple Music Preview app which are both available on the Microsoft Store for free. Just be weary though, iTunes is a terrible application and the new Apple Music Preview is somehow even buggier than iTunes.
