### ISSUE TITLE
[Bug]: Tracks missing album art show previous track's art

### ISSUE THREAD

**Issue by jacksonwelsh** [ciderapp/Sabiiro-BugTracker#21]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Operating System Version

Win11 Edu 22H2 (22621.1265)

### Describe the Bug

Rather than showing a placeholder image, tracks that don't have album art assigned use the previous track's art in the Now Playing section, and show an empty container in other UI areas.

![image](https://user-images.githubusercontent.com/20214768/223315113-a0fd7e5c-088f-4d42-acdf-536c60edb29f.png)
![image](https://user-images.githubusercontent.com/20214768/223315135-8b32a99a-89a7-472a-bbdd-127e0dbc1a6e.png)

### Steps to Reproduce

1. Upload custom music to your Apple Music Library using Cloud Library
2. Do not assign artwork to the track/album
3. View the album in Cider2

### Anything else?

Also notable- the "album" does not show a year while it shows as 2022 in the official macOS client since I've assigned this track a year of 2022.

**Comment by coredev-uk** [comment]
From testing, this seems to be resolved.
