### ISSUE TITLE
[Bug]:

### ISSUE THREAD

**Issue by Atsulu** [ciderapp/Sabiiro-BugTracker#222]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

30 may 2023

### Operating System Version

Windows 11 Pro 22H2

### Describe the Bug

#1 Bug - After logging in with my Apple a/c I got connection error message even though my connection was working properly
#2 Bug - Friends Listening icon does not appear 
#3 Bug - Minimizing & Maximizing the app does not function well
#4 Bug - End of the song lags while awaiting to play the next song
#5 Bug - MiniPlayer does not function well
#6 Bug - App Library tab does not function as it should, (Song, Album, Artist tabs does not display any content)

### Steps to Reproduce

NOTHING DONE !

### Build timestamp

1685421336282

**Comment by coredev-uk** [comment]
This isn't exactly helpful. Linking to various issues does not help us with your case. Please ensure you are on the latest version and make a new issue following the correct structure.
