### ISSUE TITLE
[Bug]: Adding song to library/loving a song via playback bar doesn't sync correctly

### ISSUE THREAD

**Issue by NotChanceBanana** [ciderapp/Sabiiro-BugTracker#26]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Operating System Version

Win 11 22H2 22621.1344

### Describe the Bug

![image](https://user-images.githubusercontent.com/123398780/223326681-bcea0dba-9bec-4395-82af-4a5c2e2c2bc9.png)
Neither of these buttons will correctly update when a song is added to your library or is loved.

### Steps to Reproduce

Right click song, try to add to library or love it.

**Comment by Blackklegend** [comment]
same here
Windows 10 Pro 22H2 19045.2846 Windows Feature Experience Pack 120.2212.4190.0

**Comment by coredev-uk** [comment]
Resolved.
