### ISSUE TITLE
[Bug]: Sorting Songslist to Title not working

### ISSUE THREAD

**Issue by FlashiFlasche** [ciderapp/Sabiiro-BugTracker#30]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Operating System Version

Windows 11 version 22H2

### Describe the Bug

When trying to sort the songs to "Title" it will sort it like the "None" sorting.

### Steps to Reproduce

1. on the left go in "Songs"
2. on the top right click the sorting button
3. sort to "Title"

![reproducing bug](https://user-images.githubusercontent.com/63459112/223347302-65acec65-31a2-4133-a25b-f1be85b10057.gif)

### Anything else?

* I don't know if it's only for some users but this bug has been present for me since the sorting system was added

**Comment by coredev-uk** [comment]
Resolved with https://github.com/ciderapp/project2/pull/12

**Comment by FlashiFlasche** [comment]
Not resolved in Sabiiro

**Comment by coredev-uk** [comment]
Sabiiro is not being built with clientdb branch atm, bug is not present in that branch.
