### ISSUE TITLE
[Bug]: Media Keys are not working

### ISSUE THREAD

**Issue by Naxterra** [ciderapp/Sabiiro-BugTracker#41]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Operating System Version

Windows 11 Enterprise 22621.1344

### Describe the Bug

Next and Previous track is not working from my keyboard and mouse. I am using Razer Synapse with Razer Huntsman v2 and Razer Naga Trinity.

No media apps are running in the background. Same keys are working with Spotify but not with Cider.

I have Cider 2.0 FujisanCore

### Steps to Reproduce

Play Next Track
nothing happens.
Play Previous Track
nothing happens
Play / Stop
it works.

**Comment by Naxterra** [comment]
> Quick question: is this happening after you saw a popup that says "Playback Error"?

There are no error messages. As an update, after several restarts and relogins it is happening less frequently

**Comment by coredev-uk** [comment]
You are certain no media apps are running (this can include Discord)?

**Comment by Naxterra** [comment]
> You are certain no media apps are running (this can include Discord)?

Yes. I am even closing browsers to prevent them hindering in the background

**Comment by coredev-uk** [comment]
Resolved with Tauri afaik.
