### ISSUE TITLE
[Bug]: Sort dropdown for Albums not sorting at all

### ISSUE THREAD

**Issue by NotChanceBanana** [ciderapp/Sabiiro-BugTracker#43]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Operating System Version

Win 11 22H2

### Describe the Bug

Similar to song list in library, album sorting also appears to be bugged, however it might be more bugged for Albums, as none of the filters actually change anything, even after attempting manual refresh.
![image](https://user-images.githubusercontent.com/123398780/223508393-8dce9fff-7971-42d1-b187-0e9215832783.png)
![image](https://user-images.githubusercontent.com/123398780/223508542-cdbbb207-9bc9-4a1a-aad3-f45508d440a7.png)

### Steps to Reproduce

Go to Albums, attempt to filter/sort the list with any of the available options, attempt to refresh manually with the refresh button.

**Comment by NotChanceBanana** [comment]
Partially fixed in latest build - now sorting by name, artist, etc. works as expected in the Songs list in Libary, but going between ascending/descending does not work.

**Comment by coredev-uk** [comment]
In my testing, this issue is no longer apparent in latest build. Please test for yourself and let me know if I'm wrong.
