### ISSUE TITLE
[Bug]: Missing texts in menus

### ISSUE THREAD

**Issue by Naxterra** [ciderapp/Sabiiro-BugTracker#45]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Operating System Version

Windows 11 Enterprise 22621.1344

### Describe the Bug

Many of the menu buttons have term. string

### Steps to Reproduce

Check menus

### Anything else?

![image](https://user-images.githubusercontent.com/41871948/223526259-5773358c-0767-4aeb-a934-29ef9135e1a6.png)

![image](https://user-images.githubusercontent.com/41871948/223526278-eb2f08fa-1138-4c88-a128-133dd48de59f.png)

![image](https://user-images.githubusercontent.com/41871948/223526293-17cf6b2c-5e50-4fff-9fb0-a3c8e2ce95d2.png)

![image](https://user-images.githubusercontent.com/41871948/223526343-524256ab-e9a4-4697-a32e-7cf7697549fe.png)

![image](https://user-images.githubusercontent.com/41871948/223526377-a5c83a5d-22e1-41e8-9d89-f2acc9e5b60a.png)

![image](https://user-images.githubusercontent.com/41871948/223526401-686062a3-6690-4fb2-89ed-1a9b51744dfc.png)

**Comment by coredev-uk** [comment]
This is a localisation failure. This may be down to your network blocking crowdin, or could be a fault with our localization function. This is the first time I've heard of someone having this issue, so it will be hard to replicate and thus fix.
