### ISSUE TITLE
[Suggestion]: Add a dedicated button for immersive mode

### ISSUE THREAD

**Issue by oEnchanted** [ciderapp/Sabiiro-BugTracker#46]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Operating System Version

All

### Describe the Bug

Immersive mode is a really nice feature to use frequently, and it would be nice to have a dedicated button next to the song information instead of having to right click and initiate it. 
![image](https://user-images.githubusercontent.com/49955460/223556433-ed384e74-ab4b-4ad9-aa8c-7e114a80dbb0.png)

### Steps to Reproduce

N/A

**Comment by coredev-uk** [comment]
This is a very small change; I will put this down to the discretion of our lead UI engineer.
