### ISSUE TITLE
[Bug]: Discord RPC and Cider Online Dashboard not working for tracks from the iCloud Library

### ISSUE THREAD

**Issue by PZeide** [ciderapp/Sabiiro-BugTracker#48]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Operating System Version

Windows 11 22H2

### Describe the Bug

When I'm playing tracks from my iCloud library, the usual "Browsing Cider" or "Playing {PREVIOUS TRACK HERE}" is showing instead of the current track. It also happens for the Connect Dashboard.

### Steps to Reproduce

1. Play any of your track from the iCloud library
2. Discord RPC and Cider Connect Dashboard isn't updating

**Comment by quacksire** [comment]
https://github.com/ciderapp/project2/pull/56
