### ISSUE TITLE
[Bug]: Entire queue got skipped 

### ISSUE THREAD

**Issue by Ravioliii** [ciderapp/Sabiiro-BugTracker#49]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Operating System Version

Windows 11 22H2

### Describe the Bug

I was listening to a non-explicit song and when that song ended my entire queue was skipped. The queue had 2 explicit songs but my content restrictions weren't changed. It went one by one and played 0.1 seconds of the next song until it reached the end of the queue. None of my keys were pressed on my laptop or usb keyboard and I was on a google tab. Reopening the app had no issues.

### Steps to Reproduce

I'm not sure that this is reproducible by any means but it is something that happened for whatever reason within the app.

**Comment by Ravioliii** [comment]
My content restrictions were never changed

**Comment by coredev-uk** [comment]
Can you check if the same behaviour occurs on https://beta.music.apple.com
