### ISSUE TITLE
[Bug]: The initial search always brings the right result, but as I go to click it, it's replaced by a totally unrelated result.

### ISSUE THREAD

**Issue by shayanz23** [ciderapp/Sabiiro-BugTracker#50]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Operating System Version

Windows 11 22H2

### Describe the Bug

When Im searching, the initial results are usually correct even before im done typing my query, but as I go to click, it is replaced by irrelevant stuff that I don't care for usually.

### Steps to Reproduce

1. use the search on the top bar 

### Anything else?
![goodSearchCider](https://user-images.githubusercontent.com/35084589/223635416-1378ab91-87d9-40cf-91b3-eb330ba0ddfc.png)
Childish Gambino replaced by CHILD before I can even click on the initial result:
![ShitySearchCider](https://user-images.githubusercontent.com/35084589/223635412-7ee3597f-a7d3-4f15-96c9-e8587ab4c321.png)

**Comment by coredev-uk** [comment]
Seems to work correctly in latest build.
