### ISSUE TITLE
[Bug]: Music skips briefly at 13 seconds from end of track

### ISSUE THREAD

**Issue by joshrsmith** [ciderapp/Sabiiro-BugTracker#53]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Operating System Version

Windows 10 19044

### Describe the Bug

About 13 seconds from the end of a track the music momentarily skips/pauses, then finishes playing the rest of the track. Probably like 100ms glitch?

### Steps to Reproduce

* Play a song (full duration, or skip to 20 seconds left, doesn't matter)
* Once -0:13 comes up, the music will briefly skip

### Anything else?

Other possible setup related things:
* Cider Audio disabled
* DRM System Default
* I use Voicemeeter with VB Cable for Cider.
* I use "App volume and device perferences" to route Cider audio to VB Cable.

**Comment by coredev-uk** [comment]
Probably a musickit bug
