### ISSUE TITLE
[Bug]: Sorting by date added doesn't work as anticipated 

### ISSUE THREAD

**Issue by Ravioliii** [ciderapp/Sabiiro-BugTracker#56]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Operating System Version

Windows 11 22H2

### Describe the Bug

I tried sorting my playlists of two sizes. One big, one small. Both do not work and sort by whatever sorting option was last chosen. 

### Steps to Reproduce

1. Go to playlists
2. Sort by date added
3. Ascending/descending inactive 
4. Click on any other sort option
5. Go back to sort by date added
6. Ascending/descending work for last chosen option

**Comment by Ravioliii** [comment]
I’m using the March 8th prerelease update

**Comment by coredev-uk** [comment]
So looking into this, it appears the API call that we previously made to fetch the songs for a playlist no longer returns a date added. I'm not too sure what's changed, I'll post any updates here.

**Comment by coredev-uk** [comment]
Resolved in https://github.com/ciderapp/project2/commit/caf23764c5985e9e550ca333e244730129f50b06
