### ISSUE TITLE
[UX Issue]: Last.FM settings are confusing

### ISSUE THREAD

**Issue by TreehouseFalcon** [ciderapp/Sabiiro-BugTracker#57]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Operating System Version

Windows 11 22H2

## Current behavior

The LastFM settings (shown below) are a bit confusing when they also exist as a Cider Connect integration. Will these be removed in the future? Right now I have LastFM linked with Cider Connect and it still says "Link LastFM" instead of "Unlink LastFM". 
Additionally, when putting in my username and password manually into the openly visible input fields (which is probably a security risk for some users on its own) and clicking "Link LastFM", it didn't actually link my account to my LastFM scrobbles.

![Cider_IJ8QcT8haL](https://user-images.githubusercontent.com/56169608/223796168-91ea72a3-517d-492a-9d1f-a78c2d35869a.png)

## Expected behavior

There should be one central location or source-of-truth for configuring LastFM, either in the Cider app settings or through Cider Connect (which I expect will be the case).

### Steps to Reproduce

1. Open settings
2. Go to Accounts
3. Locate LastFM settings

**Comment by Swiftzerr** [comment]
Most of the entire settings menu needs to be redone, lots of confusing settings and dupes

**Comment by d3rpp** [comment]
Last.fm menu gone from borderline keylogger to actual tokens, closing as irrelevant in Sabiiro builds
