### ISSUE TITLE
[Bug]: Albums list blank on latest build (3/13/23 release)

### ISSUE THREAD

**Issue by NotChanceBanana** [ciderapp/Sabiiro-BugTracker#59]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Operating System Version

Win 11 22H2

### Describe the Bug

Albums list doesnot show any albums at all, is completely blank on latest build.
![image](https://user-images.githubusercontent.com/123398780/223830308-3e9258ef-b04d-4e8b-9884-f34370b82412.png)

### Steps to Reproduce

Open C2, open albums tab. Possible ties to adding an album before opening/rendering it for the first time on that launch, restarting does not fix this issue. Sorting/refreshing has no affect on this either.

**Comment by coredev-uk** [comment]
Do you have a large music library? As the album page displays information from the database, if you have a large library it may take a minute to store the data to the database.

**Comment by PixlM** [comment]
yes, I have a large library, but it has been blank for close to an hour now, refreshing/doing anything else doesnt help either.

**Comment by coredev-uk** [comment]
The database may be failing to create. Have you tried reinstalling the app?

**Comment by PixlM** [comment]
I have,but  does Cider remove all of it's data or are there some locations I might have to go to manually clear files?

**Comment by NotChanceBanana** [comment]
This issue is partially fixed for me in latest build - it will load some albums, but after scrolling down and sitting on the page waiting for it to load for 5 minutes, I am unable to load the full list of albums i have added to my libary.
![image](https://user-images.githubusercontent.com/123398780/224992160-921fc998-d885-44fa-bd47-ee9fb7bdd0ad.png)

**Comment by coredev-uk** [comment]
Believe to have resolved in https://github.com/ciderapp/project2/commit/caf23764c5985e9e550ca333e244730129f50b06
