### ISSUE TITLE
[Bug]: Last.fm integration scrobbles at beginning of song playback

### ISSUE THREAD

**Issue by RuiNtD** [ciderapp/Sabiiro-BugTracker#6]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Operating System Version

Windows 11 22H2

### Describe the Bug

Last.fm integration should only scrobble at the end of playback or at 75% progress, otherwise you can end up with several incorrect entries, as well as your current song showing up twice.

### Steps to Reproduce

1. Log into Last.fm
2. Play a song
3. Observe your last.fm profile

### Anything else?

![image](https://user-images.githubusercontent.com/1149870/223300278-96d8abc2-ce9f-4d58-9605-7fdbc32bab4d.png)

**Comment by kobaltkloud** [comment]
"Scrobble at %" feature would be amazing!

**Comment by coredev-uk** [comment]
Implemented.
