### ISSUE TITLE
[Bug]: Out of Memory w/ClientDB test build

### ISSUE THREAD

**Issue by umbreon22** [ciderapp/Sabiiro-BugTracker#65]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Operating System Version

Windows 11 22H2

### Describe the Bug

Cider 2 produces an 'Out of Memory' error on the Fujisan ClientDB test build not long after starting up the client.

### Steps to Reproduce

1. Install Cider (Fujisan ClientDB test build)
2. Open Cider
3. Wait*
4. Error code: Out of Memory

* Visiting certain pages like songs, artists, all playlists might make it happen faster.

### Anything else?

![image](https://user-images.githubusercontent.com/25412667/223884969-1b27eb42-6c57-44b6-a0d0-e905348320fc.png)

Somet things of note:  
- My library has about 16,000 songs. 
- This does not happen on the "Latest Fujisan build for Windows" posted by freehelpdesk today.

**Comment by PixlM** [comment]
still exists on newest client
 happens when I try to change the "sort by" setting.

**Comment by coredev-uk** [comment]
Resolved with tauri.

**Comment by d3rpp** [comment]
A fix for this issue has been submitted to the microsoft store and is pending approval

The approval time is the a true random number generator, it could be 2 days, or 5 weeks

we literally don't know

**Comment by coredev-uk** [comment]
Think this is resolved now. The feedback from the latest donator build states it solved for the most part.
