### ISSUE TITLE
[Bug]: Playlist area shows white box in bottom right corner on hover

### ISSUE THREAD

**Issue by heygabet** [ciderapp/Sabiiro-BugTracker#67]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Operating System Version

Windows 11 22621.1265

### Describe the Bug

A couple behavioral issues:
Upon hovering over the playlists tab:
-A white box appears in the bottom left
-The vertical scroll bar appears instantly without an animation
-The horizontal scroll bar doesn't disappear/reappear on hover, unlike the vertical scroll bar, and is thicker than the vertical scroll bar

### Steps to Reproduce

Just hovering over the playlists section did it for me. Maybe it's because I have some playlist names that warrant the horizontal scroll bar?

### Anything else?

With no hover:
<img width="761" alt="image" src="https://user-images.githubusercontent.com/13680357/223917689-571543cd-4480-4c40-bc46-9e69efe5e39d.png">
With hover:
<img width="764" alt="image" src="https://user-images.githubusercontent.com/13680357/223917726-75409d6b-49b7-414f-9dc1-03828a9a64d2.png">

**Comment by Swiftzerr** [comment]
Are you on the latest build, neither me or core could reproduce this

**Comment by heygabet** [comment]
on new updates it seems like it went away. guess it was just me 🤷‍♂️
