### ISSUE TITLE
[Bug]: Sing Inactive lyrics' inconsistent font weight.

### ISSUE THREAD

**Issue by solibule** [ciderapp/Sabiiro-BugTracker#70]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Operating System Version

Windows 11 22H2

### Describe the Bug

![Screenshot 2023-03-09 025640](https://user-images.githubusercontent.com/75220305/223972524-34fd52ac-6665-48ab-b555-e474efcb1298.png)
![Screenshot 2023-03-09 025522](https://user-images.githubusercontent.com/75220305/223972531-13717756-0380-45fc-8b4f-627cf6353230.png)
![Screenshot 2023-03-09 025507](https://user-images.githubusercontent.com/75220305/223972532-b6d462ed-e3ef-4dcd-8a02-1c853179cd4c.png)

Songs with Sing Lyrics will sometimes fetch the wrong font weight, as seen by The Marias' song and Lorde's song, while Claude's song has the correct font weight. It's distracting and detracts from Immersive's lyric view.

### Steps to Reproduce

1. Either opening the lyrics tab on songs with Sing Lyrics enabled or entering Immersive will yield the result.

**Comment by coredev-uk** [comment]
From all my testing this seems to be working correctly now, if certain songs are experiencing this issue then it will probably be an issue with Apple's API.
