### ISSUE TITLE
[Bug]: Right clicking in Immersive does not bring up context menu.

### ISSUE THREAD

**Issue by solibule** [ciderapp/Sabiiro-BugTracker#71]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Operating System Version

Windows 11 22H2

### Describe the Bug

![Screenshot 2023-03-09 025620](https://user-images.githubusercontent.com/75220305/223973160-cb9b24da-5b12-44a8-b82a-3ce99db40dde.png)

Right clicking in Fujisan creates this dark grey circle, instead of bringing up the context menu.

### Steps to Reproduce

1. Enter Immersive.
2. Right click anywhere on the window.

**Comment by coredev-uk** [comment]
Was unable to replicate in electron-frontend.

**Comment by solibule** [comment]
This behaviour continued into Sabiiro. When right clicking when no song is loaded, the mentioned grey button appears instead of context menu.
![image](https://user-images.githubusercontent.com/75220305/227826994-32066ae2-1527-4138-8ff5-226af56e6b9f.png)
In a situation when a song is in the Now Playing section, but isn't loaded, the grey button still appears until the song is loaded on the client side, which it then fetches the song data and can now bring it up.

In Immersive, the grey button will appear only when the context menu hasnt been opened through the three dots here.
![image](https://user-images.githubusercontent.com/75220305/227827302-409596e9-5935-4b62-a604-79812ba138fa.png)

Once the context menu has been opened through the button, right clicking anywhere in Immersive correctly brings up the behaviour.
![image](https://user-images.githubusercontent.com/75220305/227827373-80c024e8-70c1-4297-8fd9-ed4a8a0e9163.png)

It seems that this Immersive behaviour resets everytime Immersive is closed, and then reopened.

**Comment by coredev-uk** [comment]
Made various recent changes, the right click option is disable however the menu can be triggered with left click on the 3 dots.
