### ISSUE TITLE
[Bug]: Queue Drawer Blocking Window Controls

### ISSUE THREAD

**Issue by JimDude7404** [ciderapp/Sabiiro-BugTracker#77]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Operating System Version

Windows 10 V. 21H2

### Describe the Bug

![image](https://user-images.githubusercontent.com/67085206/224368832-e979fef4-f841-4d11-abed-9c958c3598af.png)

Unable to click any buttons because of the window controls being in the way

### Steps to Reproduce

1. Make the window smaller
2. Attempt to press the infinity button

**Comment by coredev-uk** [comment]
I suggest turning on Use Overlay Style Drawers in settings until this is resolved.

**Comment by coredev-uk** [comment]
Appears to be resolved in latest build.
