### ISSUE TITLE
[Bug]: Songs tab list date added songs incorrectly

### ISSUE THREAD

**Issue by TheLajuj** [ciderapp/Sabiiro-BugTracker#87]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Operating System Version

Windows 11 22H2 Build 22621.1344

### Describe the Bug

when on songs tab the "Sort By" "Date Added" Sorting order feature does not show the correct order.

### Steps to Reproduce

https://user-images.githubusercontent.com/67218586/224589794-9b118f44-7f84-44a4-948b-193f66633bd9.mp4

**Comment by coredev-uk** [comment]
Are you using the latest Fujisan build?

**Comment by TheLajuj** [comment]
Yeah, latest build that Crypto has in pre-releases 

> Fujisan

**Comment by TheLajuj** [comment]
> Do you have songs that you uploaded from iTunes?

no

**Comment by kobaltkloud** [comment]
I have the same problem. Both Ascending and Descending Date Added show the same wrong order after refresh (14 March latest Fujisan build)

**Comment by coredev-uk** [comment]
Gonna close this for now, if the issue pops up on the next clientdb build, ill reopen.
