### ISSUE TITLE
[Missing]: Multiselect within playlists

### ISSUE THREAD

**Issue by oEnchanted** [ciderapp/Sabiiro-BugTracker#9]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Operating System Version

Windows 10/11/All

### Describe the Bug

Cider 1 featured multi-select within playlists that is absent from Cider 2. If you guys could bring this back it would make playlist management 100x easier 🙏 

### Steps to Reproduce

Holding shift and clicking on songs leads you to... nothing.

**Comment by coredev-uk** [comment]
Currently this is not a feature that will be implemented, it clutters up the application and keeping the playlist edit page separate helps us manage the codebase. This may be reviewed again at a later date, but this is not going to be implemented atm.
