### ISSUE TITLE
[Bug]: Discord Rich Presence Bugged on latest (3/13) build

### ISSUE THREAD

**Issue by NotChanceBanana** [ciderapp/Sabiiro-BugTracker#90]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

https://discord.com/channels/843954443845238864/905459703092490340/1085025349643010130

### Operating System Version

Win 11 22H2

### Describe the Bug

![image](https://user-images.githubusercontent.com/123398780/224993578-4b00b037-4cba-424b-b9d5-ee81f3aefcc7.png)
Current build has broken Discord Rich Presence for C2 (non Vencord version) and no longer displays currently playing song correctly. Will either display {title} by ______  (above) or Browsing Cider (below). Disabling/reenabling Rich Presence in C2 settings does NOT fix this issue.
![image](https://user-images.githubusercontent.com/123398780/224994108-23c694cc-43c9-48c2-bb94-d80e5af184af.png)

### Steps to Reproduce

Open Cider, double check that Discord Rich presence is enabled for your own Discord and C2 app settings, then check Rich Presence status on Discord to verify it's bugged. This is exclusive to the most recent build, this bug was not present on the previous build.

**Comment by BENZORICH** [comment]
I have the same problem and that when no music is playing should not be Cider RPC active but it is active with me

**Comment by coredev-uk** [comment]
Well aware of the issues with the latest Fujisan build.

**Comment by d3rpp** [comment]
Closing as Fujisan is Dead, Sabiiro has a functional discord RPC
