### ISSUE TITLE
[Bug]: Editing Playlist Causes Black Screen

### ISSUE THREAD

**Issue by CallumCM** [ciderapp/Sabiiro-BugTracker#93]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

(03/13/2023) https://discord.com/channels/843954443845238864/905459703092490340/1085025349643010130

### Operating System Version

Windows 11 Pro version 22H2 OS build 22621.1265

### Describe the Bug

Clicking on "Edit Tracklist" results in a blank screen where the playlist thumbnail is loading, and both the title and description edit boxes are blank and un-editable. The save button does nothing. The back button returns me to the playlist. This only occurs with this specific playlist, I have other playlists and they do not encounter this issue, and the playlist that does encounter the issue can be edited on Apple Music iOS and iTunes for Windows.

### Steps to Reproduce

1. Open my playlist in Cider (you need to duplicate it, I do not know if the issue will still be present)
2. Click the button with the tooltip "Edit Tracklist"

### Anything else?

The playlist with this issue is available <a href="https://music.apple.com/us/playlist/subway-but-weirder/pl.u-EdAVvvdIaxMpZg9" target="_blank">here</a>. Below is a picture of what happens when the edit tracklist button is clicked:
![Playlist Limbo](https://user-images.githubusercontent.com/51388022/225477005-2ff17f51-4ed1-47b9-adfb-58d2a3f5299f.png)

**Comment by coredev-uk** [comment]
Please try to give issues a title when you create them.

**Comment by CallumCM** [comment]
Sorry about that—I totally thought I had typed one in.

**Comment by Swiftzerr** [comment]
@CallumCM Try pressing Ctrl + Shift + I and telling me what the console says

**Comment by coredev-uk** [comment]
pretty sure console is disabled in prod

**Comment by Swiftzerr** [comment]
Hmm well i cant really debug this until we get console working in prod because this seems like an edge case. I am going to close this for now but re-open if other people start seeing this issue
