### ISSUE TITLE
[Bug]: Cider Audio Lab settings only save when main settings pane is opened and closed

### ISSUE THREAD

**Issue by DecibillyJoel** [ciderapp/Sabiiro-BugTracker#94]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

https://discord.com/channels/843954443845238864/1050090981808156672/1085686509493030992

### Operating System Version

Windows 11

### Describe the Bug

CAL settings don't save when you change them. They are only saved when the user opens and closes settings pane, which can lead to CAL settings being lost.

### Steps to Reproduce

1) Enable CAL and change any setting
2) Close Cider
3) Open Cider, check to see CAL settings are gone
4) Enable CAL and change any setting
5) Press the three dots on top left and press Settings
6) Close the settings pane
7) Close Cider
8) Open Cider, check to see CAL settings were saved

### Anything else?

This is Rust backend, not Fujisan, but I don't see any Report Bugs button in new build nor any Rust issue tracker in ciderapp repos.

**Comment by Swiftzerr** [comment]
Naw the new one is Sabriiro, get it right
