### ISSUE TITLE
[Bug]: Cannot move window unless it's with the top left corner

### ISSUE THREAD

**Issue by mpar-22** [ciderapp/Sabiiro-BugTracker#95]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

https://discord.com/channels/843954443845238864/1050090981808156672/1085840271331299328

### Operating System Version

Windows 11 22H2

### Describe the Bug

Moving the app with the title bar does not work unless it's with the top left corner. This started occurring with the first rust build but didn't happen on the first run. Every succeeding time I have opened the app, though, this issue has occurred, so I'm not entirely sure what caused it.

### Steps to Reproduce

First run:
1. Opened the app
2. Signed in, got all my settings tuned
3. Moved the window to my second monitor (normally) and resized the window
4. Closed the app

Every succeeding run:
1. Open the app
2. The window opens on my main monitor and does not reopen in the same size as before
3. Attempt to move the window, but does not work unless my cursor is on the top left corner

**Comment by d3rpp** [comment]
Are you using the setting where the player is at the top of the window?

**Comment by d3rpp** [comment]
I haven't tuned tauri to handle that issue

**Comment by mpar-22** [comment]
Yes I am, I just now tested that after deleting the folders and reinstalling like you mentioned in the discord.

**Comment by d3rpp** [comment]
you can grab it by all parts of the top bar that are not buttons or the section with playback, this behaviour is standard by apple music aswell
