### ISSUE TITLE
[Bug]: Audio Quality is randomly inconsistent when playing song from a playlist

### ISSUE THREAD

**Issue by DecibillyJoel** [ciderapp/Sabiiro-BugTracker#97]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

https://discord.com/channels/843954443845238864/1050090981808156672/1086393495150923806

### Operating System Version

Windows 11

### Describe the Bug

Sometimes the sound quality of a song will be noticeably degraded when playing from a playlist (despite Cider reporting 256 AAC, and seeking or waiting patiently doesn't fix it. only restarting the song sometimes does). It's seemingly random as you'll see in the attached video. I've tested listening to the same song through the album it comes from, and no matter how many times I tried, I haven't been able to encounter the bug when playing it that way. So I assume this bug only happens in a playlist, but I'm not sure about playing it through other means like Home page or Songs page.

### Steps to Reproduce

1. Enter a playlist
2. Play the song
3. The sound quality is sometimes noticeably reduced
4. Keep replaying the song and you'll notice it's sometimes perfectly fine and sometimes unbearable.
5. Enter the same song's album
6. Play the song
7. The sound quality will never (as far as I can tell from my testing) be reduced when playing it this way

### Anything else?

This bug has been around at least since Fujisan. I just never figured out how to reproduce it until now
Demonstration of the bug:
https://www.dropbox.com/s/jo7dvdxm0bn23x1/Cider%20Audio%20Quality%20Bug.mp4

**Comment by d3rpp** [comment]
Unfortunately due to the Widevine CDM existing
we cannot hear your audio here, though it is worth noting that in compliance with the HLS protocol (that musickit uses) if the network connection is spotty or too slow, it will automatically drop the audio quality in an effort to lower the chance of buffering.

**Comment by d3rpp** [comment]
![image](https://user-images.githubusercontent.com/45675641/226498257-28241297-5334-4a51-b7ed-820223d750c4.png)

Realistically though this is considered slow internet by todays standards

**Comment by DecibillyJoel** [comment]
> Unfortunately due to the Widevine CDM existing we cannot hear your audio here

I don't understand. I was able to play the audio back on a different browser and on my phone without issue. Are you sure the issue isn't on your end?

Regardless, try the reproduction steps I wrote out and you'll witness the bug. It happens for any song I play from a playlist or even from the Songs page on the left of the UI. It's harder to notice in some songs than others, but it's particularly prevalent in the song I used in the video, Who I'm Meant To Be by Auvic.

**Comment by d3rpp** [comment]
> > Unfortunately due to the Widevine CDM existing we cannot hear your audio here
> 
> I don't understand. I was able to play the audio back on a different browser and on my phone without issue. Are you sure the issue isn't on your end?
> 
> Regardless, try the reproduction steps I wrote out and you'll witness the bug. It happens for any song I play from a playlist or even from the Songs page on the left of the UI. It's harder to notice in some songs than others, but it's particularly prevalent in the song I used in the video, Who I'm Meant To Be by Auvic.

Widevine prevents audio from being recorded, its a hack that is overall half the reason it's so popular. for a similar effect, try screenshotting a netflix show, you'll just get a black image

**Comment by DecibillyJoel** [comment]
> > > Unfortunately due to the Widevine CDM existing we cannot hear your audio here
> > 
> > 
> > I don't understand. I was able to play the audio back on a different browser and on my phone without issue. Are you sure the issue isn't on your end?
> > Regardless, try the reproduction steps I wrote out and you'll witness the bug. It happens for any song I play from a playlist or even from the Songs page on the left of the UI. It's harder to notice in some songs than others, but it's particularly prevalent in the song I used in the video, Who I'm Meant To Be by Auvic.
> 
> Widevine prevents audio from being recorded, its a hack that is overall half the reason it's so popular. for a similar effect, try screenshotting a netflix show, you'll just get a black image

![image](https://user-images.githubusercontent.com/23534814/226499475-45ce1db1-c0a2-4068-ad32-7b2d340eaee4.png)
Audacity seems to say otherwise. I don't know if there's some kind of black magic going on here because like I said, I can play the video on my phone and hear the music from the video.

**Comment by d3rpp** [comment]
regardless, ill try and replicate your issue
