### ISSUE TITLE
[Bug]: queue and history button are black 

### ISSUE THREAD

**Issue by hmhmmhmhuh** [ciderapp/Sabiiro-BugTracker#98]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

https://discord.com/channels/843954443845238864/905459703092490340/1086396571547074560

### Operating System Version

Windows 11 / 21H2

### Describe the Bug

Queue and history button become black.

![dev_0005_896168777a343f13a44280cb62826169d91a6a28d1582ed096a5daa5a6ba9cc7](https://user-images.githubusercontent.com/65355712/226099220-b4a9ad24-8440-46d7-89f3-17b22ac8166d.png)

### Steps to Reproduce

I clicked on enable shuffle button, after i go back to the  immersive menu and this happened.

**Comment by coredev-uk** [comment]
Old bug, no longer apparent.
