### ISSUE TITLE
[Bug]: "Share with odesli" appears on station items

### ISSUE THREAD

**Issue by TreehouseFalcon** [ciderapp/Sabiiro-BugTracker#99]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

https://discord.com/channels/843954443845238864/905459703092490340/1087210306331222097

### Operating System Version

Windows 11 22H2

## Current behavior

![Cider_z5c68Fdhzs](https://user-images.githubusercontent.com/56169608/226244360-1f7f0c4e-5695-404e-b7a7-d6baa74fe4ba.png)
![Cider_I3guHyy9Xi](https://user-images.githubusercontent.com/56169608/226244638-61a7607f-e1c2-459d-b9b6-0009a956faa2.png)
![Cider_vvgLcTjVLp](https://user-images.githubusercontent.com/56169608/226244758-7164f9fd-ae5f-4164-a5ab-a58e05c0c41a.png)

As you can see above, song.link sharing appears on station, playlist, and artist items. This shouldn't be the case as Odesli doesn't support custom stations, only albums and songs.

## Expected behavior

This method of sharing should be hidden for items that aren't songs or albums.

### Steps to Reproduce

1. Right click on a station item
2. Click Share

**Comment by Monochromish** [comment]
Fixed.
